apiVersion: v1
kind: Secret
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVZVRFdTRFVLTkk3Mkk1NkIKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gNlQweHdQRFdaUGJDLzhVcXVYWnBZckpkTHVoOWtpeEZyUFBnQjNjNw==
metadata:
  name: aws-secret
  labels:
    app: udagram
type: Opaque