apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: udagram-frontend
          image: huaanhminh/udagram-frontend
          ports:
            - containerPort: 8100
