apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend-svc
  name: udagram-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      service: udagram-frontend-svc
      app: udagram
  template:
    metadata:
      labels:
        service: udagram-frontend-svc
        app: udagram
    spec:
      containers:
        - name: udagram-frontend
          image: huaanhminh/udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
